---
# -- (Optional) When using a custom network
networks:
  frontend:
    external: true
  backend:
    external: true
  testbed:
    external: true
services:
  traefik:
    image: traefik:v2.10.4
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # -- (Optional) Enable Dashboard, don't do in production
      - 8080:8080
    volumes:
      - ./config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # -- (Optional) When using Cloudflare as Cert Resolver
    environment:
      - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN
    # -- (Optional) When using a custom network
    networks:
      - frontend
      - backend
      - testbed
    restart: unless-stopped
